import * as shapes from "./shapes";
import { HINTS } from "./hints";
import type { ShapeResult } from "./shapes";
import type { SkillCategory } from "../../src/lib/ladder/level-spec";

export type LevelDescriptor = {
  levelNumber: number;
  title: string;
  description: string;
  skill: SkillCategory;
  hintKey: keyof typeof HINTS;
  build: () => ShapeResult;
};

const basicLogic: LevelDescriptor[] = [
  {
    levelNumber: 1,
    title: "มอเตอร์สายพานลำเลียงหลัก",
    description:
      "สายพานลำเลียงหลักจะทำงาน (Y0) ก็ต่อเมื่อกดปุ่ม Start (X0) และเปิดสวิตช์ Enable (X1) พร้อมกันเท่านั้น",
    skill: "basic_logic",
    hintKey: "and",
    build: () => shapes.shapeAnd(["X0", "X1"], "Y0"),
  },
  {
    levelNumber: 2,
    title: "ปั๊มน้ำสำรอง 2 สวิตช์",
    description: "ปั๊มน้ำ (Y0) ทำงานเมื่อกดสวิตช์ A (X0) หรือสวิตช์ B (X1) ตัวใดตัวหนึ่ง",
    skill: "basic_logic",
    hintKey: "or",
    build: () => shapes.shapeOr(["X0", "X1"], "Y0"),
  },
  {
    levelNumber: 3,
    title: "ประตูนิรภัยห้องเครื่อง",
    description: "มอเตอร์ (Y0) ทำงานได้เฉพาะเมื่อประตูนิรภัยปิดสนิทเท่านั้น (เซนเซอร์ประตู X0 = จริง หมายถึงประตูเปิดอยู่)",
    skill: "basic_logic",
    hintKey: "not",
    build: () => shapes.shapeNot("X0", "Y0"),
  },
  {
    levelNumber: 4,
    title: "เครื่องอัดไฮดรอลิก 3 เงื่อนไข",
    description:
      "เครื่องอัดไฮดรอลิก (Y0) จะทำงานเมื่อ: ฝาครอบปิด (X0), แรงดันน้ำมันพร้อม (X1), และกดปุ่ม Start (X2) ครบทั้ง 3 เงื่อนไข",
    skill: "basic_logic",
    hintKey: "and",
    build: () => shapes.shapeAnd(["X0", "X1", "X2"], "Y0"),
  },
  {
    levelNumber: 5,
    title: "สัญญาณเตือนไฟไหม้ 3 จุด",
    description: "สัญญาณเตือนไฟไหม้ (Y0) จะดังขึ้นเมื่อเซนเซอร์ควันจุดใดจุดหนึ่งจาก 3 จุด (X0, X1, X2) ตรวจจับได้",
    skill: "basic_logic",
    hintKey: "or",
    build: () => shapes.shapeOr(["X0", "X1", "X2"], "Y0"),
  },
  {
    levelNumber: 6,
    title: "มอเตอร์พัดลมระบายความร้อน",
    description: "พัดลม (Y0) ทำงานเมื่อกดปุ่ม Start (X0) และต้องไม่มีสัญญาณ Overload (X1) ค้างอยู่",
    skill: "basic_logic",
    hintKey: "not",
    build: () => shapes.shapeAndNot("X0", "X1", "Y0"),
  },
  {
    levelNumber: 7,
    title: "สายพานลำเลียงหลัก (E-Stop คู่)",
    description:
      "สายพานลำเลียง (Y0) ทำงานได้ตลอดเวลา ยกเว้นเมื่อมีการกดปุ่มฉุกเฉิน E-Stop จุดที่ 1 (X0) หรือจุดที่ 2 (X1)",
    skill: "basic_logic",
    hintKey: "not",
    build: () => shapes.shapeSeriesNot(["X0", "X1"], "Y0"),
  },
  {
    levelNumber: 8,
    title: "เครื่องบรรจุภัณฑ์อัตโนมัติ",
    description:
      "เครื่องบรรจุภัณฑ์ (Y0) ทำงานเมื่อ (ฝาปิดสนิท X0 และกด Start X1) หรือเมื่อกดปุ่ม Override ของหัวหน้างาน (X2)",
    skill: "basic_logic",
    hintKey: "and",
    build: () => shapes.shapeAndOrMix("X0", "X1", "X2", "Y0"),
  },
  {
    levelNumber: 9,
    title: "ระบบรดน้ำต้นไม้อัตโนมัติ",
    description: "วาล์วรดน้ำ (Y0) เปิดเมื่อความชื้นในดินต่ำ (X0) และตั้งเวลารดน้ำเปิดใช้งานอยู่ (X1) พร้อมกัน",
    skill: "basic_logic",
    hintKey: "and",
    build: () => shapes.shapeAnd(["X0", "X1"], "Y0"),
  },
  {
    levelNumber: 10,
    title: "สถานีแจ้งเหตุฉุกเฉิน 2 จุด",
    description: "สัญญาณไซเรน (Y0) ดังขึ้นเมื่อมีการกดปุ่มขอความช่วยเหลือจากจุดที่ 1 (X0) หรือจุดที่ 2 (X1)",
    skill: "basic_logic",
    hintKey: "or",
    build: () => shapes.shapeOr(["X0", "X1"], "Y0"),
  },
  {
    levelNumber: 11,
    title: "เซนเซอร์ตรวจจับสิ่งกีดขวาง",
    description: "สายพาน (Y0) เดินเครื่องได้ตามปกติ ตราบใดที่เซนเซอร์ตรวจจับวัตถุกีดขวาง (X0) ไม่พบสิ่งกีดขวาง",
    skill: "basic_logic",
    hintKey: "not",
    build: () => shapes.shapeNot("X0", "Y0"),
  },
  {
    levelNumber: 12,
    title: "ระบบล็อกประตูนิรภัย 3 ชั้น",
    description: "ประตูจะปลดล็อก (Y0) ได้ก็ต่อเมื่อผ่านการตรวจสอบครบ 3 ชั้น: บัตรผ่าน (X0), รหัสผ่าน (X1), และลายนิ้วมือ (X2)",
    skill: "basic_logic",
    hintKey: "and",
    build: () => shapes.shapeAnd(["X0", "X1", "X2"], "Y0"),
  },
  {
    levelNumber: 13,
    title: "ปุ่มขอความช่วยเหลือ 3 จุด",
    description: "กระดิ่งเรียกพนักงาน (Y0) ดังขึ้นเมื่อมีการกดปุ่มจากจุดที่ 1, 2 หรือ 3 (X0, X1, X2) จุดใดจุดหนึ่ง",
    skill: "basic_logic",
    hintKey: "or",
    build: () => shapes.shapeOr(["X0", "X1", "X2"], "Y0"),
  },
  {
    levelNumber: 14,
    title: "เครื่องเชื่อมโลหะอัตโนมัติ",
    description: "หัวเชื่อม (Y0) ทำงานเมื่อกดปุ่ม Start (X0) และฝาครอบป้องกันแสงต้องไม่เปิดอยู่ (X1)",
    skill: "basic_logic",
    hintKey: "not",
    build: () => shapes.shapeAndNot("X0", "X1", "Y0"),
  },
  {
    levelNumber: 15,
    title: "ระบบป้องกันแรงดันเกิน 2 จุด",
    description: "ปั๊มไฮดรอลิก (Y0) ทำงานได้ตามปกติ ยกเว้นเมื่อสวิตช์แรงดันเกินจุดที่ 1 (X0) หรือจุดที่ 2 (X1) ทำงาน",
    skill: "basic_logic",
    hintKey: "not",
    build: () => shapes.shapeSeriesNot(["X0", "X1"], "Y0"),
  },
  {
    levelNumber: 16,
    title: "ระบบไฟส่องสว่างอัตโนมัติ",
    description:
      "ไฟส่องสว่าง (Y0) เปิดเมื่อ (ตรวจพบความเคลื่อนไหว X0 และแสงภายนอกมืด X1) หรือเมื่อกดสวิตช์เปิดไฟด้วยมือ (X2)",
    skill: "basic_logic",
    hintKey: "and",
    build: () => shapes.shapeAndOrMix("X0", "X1", "X2", "Y0"),
  },
  {
    levelNumber: 17,
    title: "เครื่องตัดวัสดุ (สตาร์ท 2 มือ)",
    description:
      "เครื่องตัด (Y0) จะทำงานเมื่อผู้ปฏิบัติงานกดปุ่มมือซ้าย (X0) และมือขวา (X1) พร้อมกันเท่านั้น เพื่อความปลอดภัย",
    skill: "basic_logic",
    hintKey: "and",
    build: () => shapes.shapeAnd(["X0", "X1"], "Y0"),
  },
  {
    levelNumber: 18,
    title: "ระบบระบายอากาศห้องพ่นสี",
    description: "พัดลมระบายอากาศ (Y0) ทำงานเมื่อเซนเซอร์ตรวจจับไอสารเคมี (X0) หรือกดสวิตช์เปิดด้วยมือ (X1)",
    skill: "basic_logic",
    hintKey: "or",
    build: () => shapes.shapeOr(["X0", "X1"], "Y0"),
  },
  {
    levelNumber: 19,
    title: "หุ่นยนต์แขนกลอุตสาหกรรม",
    description: "แขนกล (Y0) เริ่มทำงานเมื่อ: อยู่ในโหมดอัตโนมัติ (X0), พื้นที่ทำงานปลอดภัย (X1), และมีชิ้นงานพร้อม (X2)",
    skill: "basic_logic",
    hintKey: "and",
    build: () => shapes.shapeAnd(["X0", "X1", "X2"], "Y0"),
  },
  {
    levelNumber: 20,
    title: "ระบบแจ้งเตือนอุณหภูมิสูง",
    description:
      "สัญญาณเตือน (Y0) ทำงานเมื่อ (เซนเซอร์ A ตรวจพบความร้อนสูง X0 และเซนเซอร์ B ยืนยัน X1) หรือเมื่อกดปุ่มทดสอบระบบ (X2)",
    skill: "basic_logic",
    hintKey: "and",
    build: () => shapes.shapeAndOrMix("X0", "X1", "X2", "Y0"),
  },
];

const latching: LevelDescriptor[] = [
  {
    levelNumber: 21,
    title: "สายพานลำเลียงหลัก (Start/Stop)",
    description: "กดปุ่ม Start (X0) เพื่อให้สายพาน (Y0) ทำงานค้างไว้ จนกว่าจะกดปุ่ม Stop (X1)",
    skill: "latching",
    hintKey: "latch",
    build: () => shapes.shapeLatch("X0", "X1", "Y0"),
  },
  {
    levelNumber: 22,
    title: "ปั๊มน้ำหอถังเก็บ",
    description: "กดปุ่ม Start (X0) เพื่อให้ปั๊มน้ำ (Y0) ทำงานค้างไว้ จนกว่าจะกดปุ่ม Stop (X1)",
    skill: "latching",
    hintKey: "latch",
    build: () => shapes.shapeLatch("X0", "X1", "Y0"),
  },
  {
    levelNumber: 23,
    title: "เครื่องบดวัสดุ (2 สถานีหยุด)",
    description:
      "กดปุ่ม Start (X0) เพื่อให้เครื่องบด (Y0) ทำงานค้างไว้ จนกว่าจะมีการกดปุ่ม Stop จากสถานีที่ 1 (X1) หรือสถานีที่ 2 (X2)",
    skill: "latching",
    hintKey: "latch",
    build: () => shapes.shapeLatchMultiStop("X0", "X1", "X2", "Y0"),
  },
  {
    levelNumber: 24,
    title: "กระบอกสูบลม (ยืด/หด)",
    description: "กดปุ่มยืดกระบอกสูบ (X0) เพื่อให้วาล์ว (Y0) ค้างสถานะยืดไว้ จนกว่าจะกดปุ่มหด (X1)",
    skill: "latching",
    hintKey: "latch",
    build: () => shapes.shapeLatch("X0", "X1", "Y0"),
  },
  {
    levelNumber: 25,
    title: "มอเตอร์คอมเพรสเซอร์ลม",
    description:
      "คอมเพรสเซอร์ (Y0) จะเริ่มทำงานค้างไว้เมื่อกดปุ่ม Start (X0) ในขณะที่แรงดันลมยังต่ำกว่าเกณฑ์ (X1) เท่านั้น จนกว่าจะกด Stop (X2)",
    skill: "latching",
    hintKey: "latch",
    build: () => shapes.shapeLatchGated("X0", "X1", "X2", "Y0"),
  },
  {
    levelNumber: 26,
    title: "ระบบแจ้งเตือนไฟไหม้ (Latch + Silence)",
    description: "เมื่อเซนเซอร์ควันตรวจพบ (X0) ให้สัญญาณเตือน (Y0) ค้างดังไว้ จนกว่าเจ้าหน้าที่จะกดปุ่ม Silence/Reset (X1)",
    skill: "latching",
    hintKey: "latch",
    build: () => shapes.shapeLatch("X0", "X1", "Y0"),
  },
  {
    levelNumber: 27,
    title: "เครื่องกวนสารเคมี (2 จุดฉุกเฉิน)",
    description:
      "กดปุ่ม Start (X0) เพื่อให้เครื่องกวน (Y0) ทำงานค้างไว้ จนกว่าจะมีการกดปุ่มฉุกเฉินจุดที่ 1 (X1) หรือจุดที่ 2 (X2)",
    skill: "latching",
    hintKey: "latch",
    build: () => shapes.shapeLatchMultiStop("X0", "X1", "X2", "Y0"),
  },
  {
    levelNumber: 28,
    title: "ไฟส่องสว่างโรงงาน",
    description: "กดสวิตช์เปิด (X0) เพื่อให้ไฟส่องสว่าง (Y0) ติดค้างไว้ จนกว่าจะกดสวิตช์ปิด (X1)",
    skill: "latching",
    hintKey: "latch",
    build: () => shapes.shapeLatch("X0", "X1", "Y0"),
  },
  {
    levelNumber: 29,
    title: "ระบบล็อกประตูอัตโนมัติ",
    description:
      "ระบบจะล็อกประตูค้างไว้ (Y0) เมื่อกดปุ่มล็อก (X0) ในขณะที่ประตูปิดสนิทแล้ว (X1) เท่านั้น จนกว่าจะกดปุ่มปลดล็อก (X2)",
    skill: "latching",
    hintKey: "latch",
    build: () => shapes.shapeLatchGated("X0", "X1", "X2", "Y0"),
  },
  {
    levelNumber: 30,
    title: "มอเตอร์ยกของ (Hoist)",
    description: "กดปุ่ม Start (X0) เพื่อให้มอเตอร์ยกของ (Y0) ทำงานค้างไว้ จนกว่าจะกดปุ่ม Stop (X1)",
    skill: "latching",
    hintKey: "latch",
    build: () => shapes.shapeLatch("X0", "X1", "Y0"),
  },
  {
    levelNumber: 31,
    title: "สายพานบรรจุภัณฑ์ (2 สถานีหยุด)",
    description:
      "กดปุ่ม Start (X0) เพื่อให้สายพานบรรจุภัณฑ์ (Y0) ทำงานค้างไว้ จนกว่าจะกด Stop จากสถานีที่ 1 (X1) หรือสถานีที่ 2 (X2)",
    skill: "latching",
    hintKey: "latch",
    build: () => shapes.shapeLatchMultiStop("X0", "X1", "X2", "Y0"),
  },
  {
    levelNumber: 32,
    title: "ปั๊มไฮดรอลิกหลัก",
    description: "กดปุ่ม Start (X0) เพื่อให้ปั๊มไฮดรอลิก (Y0) ทำงานค้างไว้ จนกว่าจะกดปุ่ม Stop (X1)",
    skill: "latching",
    hintKey: "latch",
    build: () => shapes.shapeLatch("X0", "X1", "Y0"),
  },
  {
    levelNumber: 33,
    title: "เครื่องอัดขึ้นรูปพลาสติก",
    description:
      "กดปุ่ม Start (X0) เพื่อให้เครื่องอัดขึ้นรูป (Y0) ทำงานค้างไว้ โดยต้องมีการ์ดป้องกันปิดสนิทก่อน (X1) จนกว่าจะกด Stop (X2)",
    skill: "latching",
    hintKey: "latch",
    build: () => shapes.shapeLatchGated("X0", "X1", "X2", "Y0"),
  },
  {
    levelNumber: 34,
    title: "ระบบทำความเย็น (Chiller)",
    description: "กดปุ่ม Start (X0) เพื่อให้ระบบทำความเย็น (Y0) ทำงานค้างไว้ จนกว่าจะกดปุ่ม Stop (X1)",
    skill: "latching",
    hintKey: "latch",
    build: () => shapes.shapeLatch("X0", "X1", "Y0"),
  },
  {
    levelNumber: 35,
    title: "เครื่องกลึงโลหะ (2 สถานีหยุด)",
    description:
      "กดปุ่ม Start (X0) เพื่อให้เครื่องกลึง (Y0) ทำงานค้างไว้ จนกว่าจะกด Stop จากสถานีควบคุมหลัก (X1) หรือสถานีสำรอง (X2)",
    skill: "latching",
    hintKey: "latch",
    build: () => shapes.shapeLatchMultiStop("X0", "X1", "X2", "Y0"),
  },
  {
    levelNumber: 36,
    title: "วาล์วน้ำมันไฮดรอลิก",
    description: "กดปุ่มเปิด (X0) เพื่อให้วาล์วโซลินอยด์ (Y0) เปิดค้างไว้ จนกว่าจะกดปุ่มปิด (X1)",
    skill: "latching",
    hintKey: "latch",
    build: () => shapes.shapeLatch("X0", "X1", "Y0"),
  },
  {
    levelNumber: 37,
    title: "หุ่นยนต์เชื่อมอัตโนมัติ",
    description:
      "กดปุ่ม Start (X0) เพื่อให้หุ่นยนต์เชื่อม (Y0) ทำงานค้างไว้ โดยต้องอยู่ในโหมดอัตโนมัติก่อน (X1) จนกว่าจะกด Stop (X2)",
    skill: "latching",
    hintKey: "latch",
    build: () => shapes.shapeLatchGated("X0", "X1", "X2", "Y0"),
  },
  {
    levelNumber: 38,
    title: "พัดลมระบายความร้อนตู้ควบคุม",
    description: "กดปุ่ม Start (X0) เพื่อให้พัดลม (Y0) ทำงานค้างไว้ จนกว่าจะกดปุ่ม Stop (X1)",
    skill: "latching",
    hintKey: "latch",
    build: () => shapes.shapeLatch("X0", "X1", "Y0"),
  },
  {
    levelNumber: 39,
    title: "เครื่องบรรจุขวด (2 สถานีหยุด)",
    description:
      "กดปุ่ม Start (X0) เพื่อให้เครื่องบรรจุขวด (Y0) ทำงานค้างไว้ จนกว่าจะกด Stop จากต้นสาย (X1) หรือปลายสาย (X2)",
    skill: "latching",
    hintKey: "latch",
    build: () => shapes.shapeLatchMultiStop("X0", "X1", "X2", "Y0"),
  },
  {
    levelNumber: 40,
    title: "ระบบสัญญาณเตือนภัยโรงงาน",
    description: "เมื่อกดปุ่มแจ้งเหตุ (X0) ให้สัญญาณเตือนภัย (Y0) ดังค้างไว้ จนกว่าเจ้าหน้าที่รักษาความปลอดภัยจะกดปุ่มยกเลิก (X1)",
    skill: "latching",
    hintKey: "latch",
    build: () => shapes.shapeLatch("X0", "X1", "Y0"),
  },
];

const timers: LevelDescriptor[] = [
  {
    levelNumber: 41,
    title: "ปั๊มน้ำหน่วงเวลาเริ่มทำงาน",
    description: "เมื่อกดปุ่ม Start (X0) ให้ปั๊มน้ำ (Y0) เริ่มทำงานหลังจากผ่านไป 3 จังหวะเวลา (ticks) เพื่อรอแรงดันระบบคงที่ก่อน",
    skill: "timers",
    hintKey: "timer_on",
    build: () => shapes.shapeTonDelay("X0", "Y0", 3),
  },
  {
    levelNumber: 42,
    title: "พัดลมระบายความร้อนเครื่องยนต์",
    description: "เมื่อเครื่องยนต์ทำงาน (X0) พัดลม (Y0) จะติดทันที และต้องหน่วงเวลาดับอีก 2 ticks หลังเครื่องยนต์ดับ เพื่อระบายความร้อนที่เหลือ",
    skill: "timers",
    hintKey: "timer_off",
    build: () => shapes.shapeTofDelay("X0", "Y0", 2),
  },
  {
    levelNumber: 43,
    title: "ตัวนับเวลาสะสมการทำงานเครื่องจักร",
    description:
      "เครื่องจักรทำงาน (X0) จะสะสมเวลาการทำงานไว้ เมื่อสะสมครบ 4 ticks ให้แจ้งเตือนบำรุงรักษา (Y0) เวลาที่สะสมจะไม่หายแม้เครื่องจะหยุดพักชั่วคราว เว้นแต่กดปุ่มรีเซ็ต (X1)",
    skill: "timers",
    hintKey: "timer_rto",
    build: () => shapes.shapeRtoAccumulate("X0", "X1", "Y0", 4),
  },
  {
    levelNumber: 44,
    title: "เครื่องผสมสารเคมี (มีฝาปิด)",
    description: "เครื่องผสม (Y0) จะเริ่มนับเวลาก็ต่อเมื่อกด Start (X0) และฝาปิดสนิท (X1) พร้อมกัน หลังผ่านไป 3 ticks เครื่องจะเริ่มทำงาน",
    skill: "timers",
    hintKey: "timer_on",
    build: () => shapes.shapeTonGated("X0", "X1", "Y0", 3),
  },
  {
    levelNumber: 45,
    title: "สัญญาณไฟจราจร 2 จังหวะ",
    description:
      "เมื่อเริ่มระบบ (X0) ไฟแดง (Y0) จะติดหลังผ่านไป 2 ticks จากนั้นไฟเขียว (Y1) จะติดอีกครั้งหลังผ่านไปอีก 2 ticks",
    skill: "timers",
    hintKey: "mixed",
    build: () => shapes.shapeTwoStageSequence("X0", "Y0", "Y1", 2, 2),
  },
  {
    levelNumber: 46,
    title: "เตาอบอุตสาหกรรม (ดีเลย์อุ่นเครื่อง)",
    description: "เมื่อกดปุ่ม Start (X0) ฮีตเตอร์เตาอบ (Y0) จะทำงานหลังจากผ่านไป 4 ticks เพื่อรอระบบระบายอากาศเริ่มทำงานก่อน",
    skill: "timers",
    hintKey: "timer_on",
    build: () => shapes.shapeTonDelay("X0", "Y0", 4),
  },
  {
    levelNumber: 47,
    title: "ไฟฉุกเฉินหน่วงเวลาดับ",
    description: "เมื่อไฟฟ้าดับ (X0) ไฟฉุกเฉิน (Y0) จะติดทันที และต้องหน่วงเวลาดับอีก 3 ticks หลังไฟฟ้ากลับมาใช้งานได้",
    skill: "timers",
    hintKey: "timer_off",
    build: () => shapes.shapeTofDelay("X0", "Y0", 3),
  },
  {
    levelNumber: 48,
    title: "ตัวนับชั่วโมงบำรุงรักษาคอมเพรสเซอร์",
    description:
      "คอมเพรสเซอร์ทำงาน (X0) จะสะสมชั่วโมงทำงานไว้ เมื่อครบ 5 ticks ให้แจ้งเตือนบำรุงรักษา (Y0) ค่าที่สะสมจะไม่หายแม้หยุดพัก เว้นแต่กดปุ่มรีเซ็ตหลังบำรุงรักษาเสร็จ (X1)",
    skill: "timers",
    hintKey: "timer_rto",
    build: () => shapes.shapeRtoAccumulate("X0", "X1", "Y0", 5),
  },
  {
    levelNumber: 49,
    title: "ถังผสมคอนกรีต (มีฝาปิด)",
    description: "ถังผสมคอนกรีต (Y0) จะเริ่มนับเวลาก็ต่อเมื่อกด Start (X0) และฝาปิดสนิท (X1) พร้อมกัน หลังผ่านไป 4 ticks เครื่องจะเริ่มหมุนผสม",
    skill: "timers",
    hintKey: "timer_on",
    build: () => shapes.shapeTonGated("X0", "X1", "Y0", 4),
  },
  {
    levelNumber: 50,
    title: "ลำดับสตาร์ทมอเตอร์ 2 จังหวะ",
    description:
      "เมื่อกดปุ่มเริ่มระบบ (X0) มอเตอร์ตัวที่ 1 (Y0) จะทำงานหลังผ่านไป 3 ticks จากนั้นมอเตอร์ตัวที่ 2 (Y1) จะทำงานอีกครั้งหลังผ่านไปอีก 2 ticks",
    skill: "timers",
    hintKey: "mixed",
    build: () => shapes.shapeTwoStageSequence("X0", "Y0", "Y1", 3, 2),
  },
  {
    levelNumber: 51,
    title: "ประตูอัตโนมัติหน่วงเวลาปิด",
    description: "เมื่อไม่มีคนผ่าน (X0=false) ประตู (Y0) จะปิดหลังจากผ่านไป 2 ticks นับจากตรวจไม่พบคนผ่าน",
    skill: "timers",
    hintKey: "timer_on",
    build: () => shapes.shapeTonDelay("X0", "Y0", 2),
  },
  {
    levelNumber: 52,
    title: "ไฟส่องสว่างลานจอดรถ",
    description: "เมื่อตรวจพบความเคลื่อนไหว (X0) ไฟ (Y0) จะติดทันที และหน่วงเวลาดับอีก 4 ticks หลังไม่มีความเคลื่อนไหวแล้ว",
    skill: "timers",
    hintKey: "timer_off",
    build: () => shapes.shapeTofDelay("X0", "Y0", 4),
  },
  {
    levelNumber: 53,
    title: "ตัวจับเวลาสะสมสายพานลำเลียง",
    description:
      "สายพานทำงาน (X0) จะสะสมเวลาไว้ เมื่อครบ 3 ticks ให้แจ้งเตือนตรวจสอบสายพาน (Y0) ค่าที่สะสมจะไม่หายไปเว้นแต่กดปุ่มรีเซ็ต (X1)",
    skill: "timers",
    hintKey: "timer_rto",
    build: () => shapes.shapeRtoAccumulate("X0", "X1", "Y0", 3),
  },
  {
    levelNumber: 54,
    title: "เครื่องล้างชิ้นงานอัตโนมัติ",
    description: "เครื่องล้าง (Y0) จะเริ่มนับเวลาก็ต่อเมื่อกด Start (X0) และตรวจพบชิ้นงานในตำแหน่ง (X1) พร้อมกัน หลังผ่านไป 2 ticks เครื่องจะเริ่มฉีดน้ำ",
    skill: "timers",
    hintKey: "timer_on",
    build: () => shapes.shapeTonGated("X0", "X1", "Y0", 2),
  },
  {
    levelNumber: 55,
    title: "ระบบเปิดวาล์วตามลำดับ",
    description:
      "เมื่อเริ่มกระบวนการ (X0) วาล์วที่ 1 (Y0) จะเปิดหลังผ่านไป 2 ticks จากนั้นวาล์วที่ 2 (Y1) จะเปิดอีกครั้งหลังผ่านไปอีก 3 ticks",
    skill: "timers",
    hintKey: "mixed",
    build: () => shapes.shapeTwoStageSequence("X0", "Y0", "Y1", 2, 3),
  },
  {
    levelNumber: 56,
    title: "ระบบพ่นสีอัตโนมัติ",
    description: "เมื่อกดปุ่ม Start (X0) หัวพ่นสี (Y0) จะทำงานหลังจากผ่านไป 5 ticks เพื่อรอแรงดันลมอัดในระบบให้คงที่ก่อน",
    skill: "timers",
    hintKey: "timer_on",
    build: () => shapes.shapeTonDelay("X0", "Y0", 5),
  },
  {
    levelNumber: 57,
    title: "พัดลมระบายอากาศห้องเครื่อง",
    description: "เมื่อเครื่องจักรทำงาน (X0) พัดลม (Y0) จะติดทันที และหน่วงเวลาดับอีก 2 ticks หลังเครื่องจักรหยุดทำงาน",
    skill: "timers",
    hintKey: "timer_off",
    build: () => shapes.shapeTofDelay("X0", "Y0", 2),
  },
  {
    levelNumber: 58,
    title: "ตัวนับเวลาใช้งานปั๊มน้ำมัน",
    description:
      "ปั๊มทำงาน (X0) จะสะสมเวลาไว้ เมื่อครบ 4 ticks ให้แจ้งเตือนเปลี่ยนน้ำมันกรอง (Y0) ค่าที่สะสมจะไม่หายไปเว้นแต่กดปุ่มรีเซ็ต (X1)",
    skill: "timers",
    hintKey: "timer_rto",
    build: () => shapes.shapeRtoAccumulate("X0", "X1", "Y0", 4),
  },
  {
    levelNumber: 59,
    title: "เครื่องนึ่งฆ่าเชื้อ (Autoclave)",
    description: "เครื่องนึ่งฆ่าเชื้อ (Y0) จะเริ่มนับเวลาก็ต่อเมื่อกด Start (X0) และฝาปิดล็อกสนิท (X1) พร้อมกัน หลังผ่านไป 3 ticks จะเริ่มทำงาน",
    skill: "timers",
    hintKey: "timer_on",
    build: () => shapes.shapeTonGated("X0", "X1", "Y0", 3),
  },
  {
    levelNumber: 60,
    title: "กระบวนการอบชุบโลหะ",
    description:
      "เมื่อเริ่มกระบวนการ (X0) ขั้นตอนอุ่นเตา (Y0) จะเริ่มหลังผ่านไป 4 ticks จากนั้นขั้นตอนชุบแข็ง (Y1) จะเริ่มอีกครั้งหลังผ่านไปอีก 2 ticks",
    skill: "timers",
    hintKey: "mixed",
    build: () => shapes.shapeTwoStageSequence("X0", "Y0", "Y1", 4, 2),
  },
  {
    levelNumber: 61,
    title: "ลิฟต์ขนส่งสินค้าหน่วงเวลา",
    description: "เมื่อกดปุ่มเรียกลิฟต์ (X0) ประตูลิฟต์ (Y0) จะเปิดหลังจากผ่านไป 3 ticks เพื่อรอลิฟต์เคลื่อนที่มาถึงชั้นก่อน",
    skill: "timers",
    hintKey: "timer_on",
    build: () => shapes.shapeTonDelay("X0", "Y0", 3),
  },
  {
    levelNumber: 62,
    title: "ไฟเตือนเครื่องจักรหน่วงดับ",
    description: "เมื่อเครื่องจักรแจ้งเตือน (X0) ไฟเตือน (Y0) จะติดทันที และหน่วงเวลาดับอีก 3 ticks หลังสถานะกลับปกติ เพื่อให้ผู้ปฏิบัติงานสังเกตเห็น",
    skill: "timers",
    hintKey: "timer_off",
    build: () => shapes.shapeTofDelay("X0", "Y0", 3),
  },
  {
    levelNumber: 63,
    title: "ตัวนับเวลาสะสมคอมเพรสเซอร์สำรอง",
    description:
      "คอมเพรสเซอร์สำรองทำงาน (X0) จะสะสมเวลาไว้ เมื่อครบ 6 ticks ให้แจ้งเตือนบำรุงรักษา (Y0) ค่าที่สะสมจะไม่หายไปเว้นแต่กดปุ่มรีเซ็ต (X1)",
    skill: "timers",
    hintKey: "timer_rto",
    build: () => shapes.shapeRtoAccumulate("X0", "X1", "Y0", 6),
  },
  {
    levelNumber: 64,
    title: "เครื่องพาสเจอร์ไรส์นม",
    description: "เครื่องพาสเจอร์ไรส์ (Y0) จะเริ่มนับเวลาก็ต่อเมื่อกด Start (X0) และอุณหภูมิถึงเกณฑ์ (X1) พร้อมกัน หลังผ่านไป 4 ticks จะเริ่มทำงาน",
    skill: "timers",
    hintKey: "timer_on",
    build: () => shapes.shapeTonGated("X0", "X1", "Y0", 4),
  },
  {
    levelNumber: 65,
    title: "ระบบล้างทำความสะอาดอัตโนมัติ (CIP)",
    description:
      "เมื่อเริ่มรอบล้าง (X0) ขั้นตอนล้างด้วยน้ำ (Y0) จะเริ่มหลังผ่านไป 3 ticks จากนั้นขั้นตอนล้างด้วยน้ำยาฆ่าเชื้อ (Y1) จะเริ่มอีกครั้งหลังผ่านไปอีก 3 ticks",
    skill: "timers",
    hintKey: "mixed",
    build: () => shapes.shapeTwoStageSequence("X0", "Y0", "Y1", 3, 3),
  },
  {
    levelNumber: 66,
    title: "วาล์วน้ำหน่วงเวลาเปิด",
    description: "เมื่อกดปุ่มเปิดวาล์ว (X0) วาล์วน้ำ (Y0) จะเปิดหลังจากผ่านไป 2 ticks เพื่อรอระบบตรวจสอบแรงดันก่อน",
    skill: "timers",
    hintKey: "timer_on",
    build: () => shapes.shapeTonDelay("X0", "Y0", 2),
  },
  {
    levelNumber: 67,
    title: "ไฟถนนหน่วงดับตอนเช้า",
    description: "เมื่อเซนเซอร์แสงตรวจพบความมืด (X0) ไฟถนน (Y0) จะติดทันที และหน่วงเวลาดับอีก 5 ticks หลังฟ้าสว่างแล้ว",
    skill: "timers",
    hintKey: "timer_off",
    build: () => shapes.shapeTofDelay("X0", "Y0", 5),
  },
  {
    levelNumber: 68,
    title: "ตัวนับชั่วโมงมอเตอร์หลักโรงงาน",
    description:
      "มอเตอร์หลักทำงาน (X0) จะสะสมชั่วโมงไว้ เมื่อครบ 3 ticks ให้แจ้งเตือนตรวจเช็คตามระยะ (Y0) ค่าที่สะสมจะไม่หายไปเว้นแต่กดปุ่มรีเซ็ต (X1)",
    skill: "timers",
    hintKey: "timer_rto",
    build: () => shapes.shapeRtoAccumulate("X0", "X1", "Y0", 3),
  },
  {
    levelNumber: 69,
    title: "เครื่องแพ็คสูญญากาศ",
    description: "เครื่องแพ็คสูญญากาศ (Y0) จะเริ่มนับเวลาก็ต่อเมื่อกด Start (X0) และฝาครอบปิดสนิท (X1) พร้อมกัน หลังผ่านไป 2 ticks จะเริ่มดูดอากาศ",
    skill: "timers",
    hintKey: "timer_on",
    build: () => shapes.shapeTonGated("X0", "X1", "Y0", 2),
  },
  {
    levelNumber: 70,
    title: "ลำดับปิดเครื่องจักรอัตโนมัติ",
    description:
      "เมื่อกดปุ่มปิดระบบ (X0) ขั้นตอนหยุดป้อนวัตถุดิบ (Y0) จะเริ่มหลังผ่านไป 2 ticks จากนั้นขั้นตอนตัดไฟหลัก (Y1) จะทำงานอีกครั้งหลังผ่านไปอีก 4 ticks",
    skill: "timers",
    hintKey: "mixed",
    build: () => shapes.shapeTwoStageSequence("X0", "Y0", "Y1", 2, 4),
  },
];

const counters: LevelDescriptor[] = [
  {
    levelNumber: 71,
    title: "นับขวดบรรจุกล่อง",
    description: "เซนเซอร์นับขวดที่ผ่าน (X0) ทุกครั้งที่มีขวดผ่าน 1 ใบ เมื่อครบ 12 ขวดให้สัญญาณปิดกล่อง (Y0) ทำงาน",
    skill: "counters",
    hintKey: "counter_up",
    build: () => shapes.shapeCtuCount("X0", "Y0", 12),
  },
  {
    levelNumber: 72,
    title: "นับถอยหลังชิ้นงานคงเหลือในชุดผลิต",
    description: "ชุดผลิตเริ่มต้นที่ 10 ชิ้น ทุกครั้งที่ผลิตเสร็จ 1 ชิ้น (X0) ตัวนับจะลดลง 1 เมื่อถึง 0 ให้สัญญาณ 'ชุดผลิตครบแล้ว' (Y0) ทำงาน",
    skill: "counters",
    hintKey: "counter_down",
    build: () => shapes.shapeCtdCount("X0", "Y0", 10),
  },
  {
    levelNumber: 73,
    title: "นับกล่องสินค้าพร้อมปุ่มรีเซ็ต",
    description: "เซนเซอร์นับกล่องที่ผ่าน (X0) เมื่อครบ 6 กล่องให้สัญญาณเตือน (Y0) ทำงาน และกดปุ่มรีเซ็ต (X1) เพื่อเริ่มนับรอบใหม่หลังขนย้ายเสร็จ",
    skill: "counters",
    hintKey: "counter_up",
    build: () => shapes.shapeCtuWithReset("X0", "X1", "Y0", 6),
  },
  {
    levelNumber: 74,
    title: "นับชิ้นงานเฉพาะขณะสายพานทำงาน",
    description: "เซนเซอร์ตรวจจับชิ้นงาน (X0) จะถูกนับก็ต่อเมื่อสายพานกำลังทำงานอยู่ (X1) เท่านั้น เมื่อครบ 5 ชิ้นให้ Y0 ทำงาน",
    skill: "counters",
    hintKey: "counter_up",
    build: () => shapes.shapeCtuGated("X0", "X1", "Y0", 5),
  },
  {
    levelNumber: 75,
    title: "ระบบหยิบจับชิ้นงาน (Pick and Place)",
    description: "แขนกลหยิบชิ้นงาน (X0) ทุกครั้งที่หยิบสำเร็จตัวนับจะเพิ่มขึ้น เมื่อหยิบครบ 5 ชิ้นให้รอ 2 ticks เพื่อความนิ่ง แล้วจึงเปิดสัญญาณพร้อมส่งออก (Y0)",
    skill: "counters",
    hintKey: "mixed",
    build: () => shapes.shapeCounterThenTimer("X0", "Y0", 5, 2),
  },
  {
    levelNumber: 76,
    title: "นับกระป๋องเครื่องดื่มต่อแพ็ค",
    description: "เซนเซอร์นับกระป๋องที่ผ่าน (X0) เมื่อครบ 8 กระป๋องให้สัญญาณห่อพลาสติก (Y0) ทำงาน",
    skill: "counters",
    hintKey: "counter_up",
    build: () => shapes.shapeCtuCount("X0", "Y0", 8),
  },
  {
    levelNumber: 77,
    title: "นับถอยหลังวัตถุดิบคงคลัง",
    description: "คลังเริ่มต้นที่ 20 หน่วย ทุกครั้งที่เบิกใช้ 1 หน่วย (X0) ตัวนับจะลดลง 1 เมื่อถึง 0 ให้สัญญาณ 'วัตถุดิบหมด' (Y0) ทำงาน",
    skill: "counters",
    hintKey: "counter_down",
    build: () => shapes.shapeCtdCount("X0", "Y0", 20),
  },
  {
    levelNumber: 78,
    title: "นับรอบการอัดขึ้นรูป",
    description: "เซนเซอร์นับรอบการอัดขึ้นรูปแต่ละครั้ง (X0) เมื่อครบ 10 รอบให้สัญญาณเปลี่ยนแม่พิมพ์ (Y0) ทำงาน และกดปุ่มรีเซ็ต (X1) หลังเปลี่ยนแม่พิมพ์เสร็จ",
    skill: "counters",
    hintKey: "counter_up",
    build: () => shapes.shapeCtuWithReset("X0", "X1", "Y0", 10),
  },
  {
    levelNumber: 79,
    title: "นับชิ้นงานเฉพาะเมื่อเปิดสวิตช์ผลิต",
    description: "เซนเซอร์ตรวจจับชิ้นงาน (X0) จะถูกนับก็ต่อเมื่อสวิตช์โหมดผลิตเปิดอยู่ (X1) เท่านั้น เมื่อครบ 4 ชิ้นให้ Y0 ทำงาน",
    skill: "counters",
    hintKey: "counter_up",
    build: () => shapes.shapeCtuGated("X0", "X1", "Y0", 4),
  },
  {
    levelNumber: 80,
    title: "ระบบจัดเรียงสินค้าอัตโนมัติ",
    description: "เซนเซอร์นับสินค้าที่จัดเรียงสำเร็จ (X0) เมื่อครบ 3 ชิ้นให้รอ 3 ticks เพื่อตรวจสอบตำแหน่ง แล้วจึงเปิดสัญญาณพร้อมส่งชั้นถัดไป (Y0)",
    skill: "counters",
    hintKey: "mixed",
    build: () => shapes.shapeCounterThenTimer("X0", "Y0", 3, 3),
  },
  {
    levelNumber: 81,
    title: "นับพาเลทสินค้าเข้าคลัง",
    description: "เซนเซอร์นับพาเลทที่เข้าคลัง (X0) เมื่อครบ 6 พาเลทให้สัญญาณ 'คลังโซนนี้เต็ม' (Y0) ทำงาน",
    skill: "counters",
    hintKey: "counter_up",
    build: () => shapes.shapeCtuCount("X0", "Y0", 6),
  },
  {
    levelNumber: 82,
    title: "นับถอยหลังรอบการทดสอบ",
    description: "ชุดทดสอบเริ่มต้นที่ 15 รอบ ทุกครั้งที่ทดสอบเสร็จ 1 รอบ (X0) ตัวนับจะลดลง 1 เมื่อถึง 0 ให้สัญญาณ 'ทดสอบครบแล้ว' (Y0) ทำงาน",
    skill: "counters",
    hintKey: "counter_down",
    build: () => shapes.shapeCtdCount("X0", "Y0", 15),
  },
  {
    levelNumber: 83,
    title: "นับชิ้นงานต่อรอบการผลิต",
    description: "เซนเซอร์นับชิ้นงานที่ผลิตได้ (X0) เมื่อครบ 12 ชิ้นให้สัญญาณจบรอบผลิต (Y0) ทำงาน และกดปุ่มรีเซ็ต (X1) เพื่อเริ่มรอบใหม่",
    skill: "counters",
    hintKey: "counter_up",
    build: () => shapes.shapeCtuWithReset("X0", "X1", "Y0", 12),
  },
  {
    levelNumber: 84,
    title: "นับสัญญาณเฉพาะช่วงเครื่องเดินเครื่อง",
    description: "พัลส์จากเซนเซอร์ความเร็ว (X0) จะถูกนับก็ต่อเมื่อเครื่องจักรอยู่ในสถานะเดินเครื่อง (X1) เท่านั้น เมื่อครบ 3 พัลส์ให้ Y0 ทำงาน",
    skill: "counters",
    hintKey: "counter_up",
    build: () => shapes.shapeCtuGated("X0", "X1", "Y0", 3),
  },
  {
    levelNumber: 85,
    title: "ระบบตรวจสอบคุณภาพอัตโนมัติ",
    description: "เซนเซอร์นับชิ้นงานที่ผ่านจุดตรวจสอบ (X0) เมื่อครบ 4 ชิ้นให้รอ 2 ticks เพื่อประมวลผล แล้วจึงเปิดสัญญาณสรุปผล (Y0)",
    skill: "counters",
    hintKey: "mixed",
    build: () => shapes.shapeCounterThenTimer("X0", "Y0", 4, 2),
  },
  {
    levelNumber: 86,
    title: "นับถุงบรรจุภัณฑ์",
    description: "เซนเซอร์นับถุงที่บรรจุเสร็จ (X0) เมื่อครบ 10 ถุงให้สัญญาณเปลี่ยนม้วนฟิล์ม (Y0) ทำงาน",
    skill: "counters",
    hintKey: "counter_up",
    build: () => shapes.shapeCtuCount("X0", "Y0", 10),
  },
  {
    levelNumber: 87,
    title: "นับถอยหลังชุดทดสอบคุณภาพ",
    description: "ชุดทดสอบคุณภาพเริ่มต้นที่ 8 ชิ้น ทุกครั้งที่ตรวจสอบเสร็จ 1 ชิ้น (X0) ตัวนับจะลดลง 1 เมื่อถึง 0 ให้สัญญาณ 'ตรวจครบชุดแล้ว' (Y0) ทำงาน",
    skill: "counters",
    hintKey: "counter_down",
    build: () => shapes.shapeCtdCount("X0", "Y0", 8),
  },
  {
    levelNumber: 88,
    title: "นับรอบเครื่องปั๊มไฮดรอลิก",
    description: "เซนเซอร์นับรอบการปั๊มแต่ละครั้ง (X0) เมื่อครบ 15 รอบให้สัญญาณตรวจเช็คน้ำมันไฮดรอลิก (Y0) ทำงาน และกดปุ่มรีเซ็ต (X1) หลังตรวจเช็คเสร็จ",
    skill: "counters",
    hintKey: "counter_up",
    build: () => shapes.shapeCtuWithReset("X0", "X1", "Y0", 15),
  },
  {
    levelNumber: 89,
    title: "นับชิ้นงานเฉพาะโหมดอัตโนมัติ",
    description: "เซนเซอร์ตรวจจับชิ้นงาน (X0) จะถูกนับก็ต่อเมื่อระบบอยู่ในโหมดอัตโนมัติ (X1) เท่านั้น เมื่อครบ 6 ชิ้นให้ Y0 ทำงาน",
    skill: "counters",
    hintKey: "counter_up",
    build: () => shapes.shapeCtuGated("X0", "X1", "Y0", 6),
  },
  {
    levelNumber: 90,
    title: "ระบบคัดแยกสินค้าไม่ได้มาตรฐาน",
    description: "เซนเซอร์นับสินค้าที่ถูกคัดออก (X0) เมื่อครบ 5 ชิ้นให้รอ 2 ticks เพื่อยืนยัน แล้วจึงเปิดสัญญาณแจ้งหัวหน้างาน (Y0)",
    skill: "counters",
    hintKey: "mixed",
    build: () => shapes.shapeCounterThenTimer("X0", "Y0", 5, 2),
  },
  {
    levelNumber: 91,
    title: "นับรถเข็นเข้าคลังสินค้า",
    description: "เซนเซอร์นับรถเข็นที่เข้าคลัง (X0) เมื่อครบ 5 คันให้สัญญาณ 'คิวโหลดสินค้าเต็ม' (Y0) ทำงาน",
    skill: "counters",
    hintKey: "counter_up",
    build: () => shapes.shapeCtuCount("X0", "Y0", 5),
  },
  {
    levelNumber: 92,
    title: "นับถอยหลังชิ้นส่วนประกอบ",
    description: "ชุดชิ้นส่วนเริ่มต้นที่ 12 ชิ้น ทุกครั้งที่ประกอบเสร็จ 1 ชิ้น (X0) ตัวนับจะลดลง 1 เมื่อถึง 0 ให้สัญญาณ 'ประกอบครบชุดแล้ว' (Y0) ทำงาน",
    skill: "counters",
    hintKey: "counter_down",
    build: () => shapes.shapeCtdCount("X0", "Y0", 12),
  },
  {
    levelNumber: 93,
    title: "นับกล่องพร้อมรีเซ็ตท้ายกะ",
    description: "เซนเซอร์นับกล่องสินค้าที่ผลิตได้ (X0) เมื่อครบ 8 กล่องให้สัญญาณแจ้งเตือน (Y0) ทำงาน และกดปุ่มรีเซ็ต (X1) เมื่อเริ่มกะทำงานใหม่",
    skill: "counters",
    hintKey: "counter_up",
    build: () => shapes.shapeCtuWithReset("X0", "X1", "Y0", 8),
  },
  {
    levelNumber: 94,
    title: "นับสัญญาณเซนเซอร์เฉพาะช่วงตรวจสอบ",
    description: "พัลส์จากเซนเซอร์ตรวจจับ (X0) จะถูกนับก็ต่อเมื่อระบบอยู่ในโหมดตรวจสอบ (X1) เท่านั้น เมื่อครบ 7 พัลส์ให้ Y0 ทำงาน",
    skill: "counters",
    hintKey: "counter_up",
    build: () => shapes.shapeCtuGated("X0", "X1", "Y0", 7),
  },
  {
    levelNumber: 95,
    title: "ระบบบรรจุอัตโนมัติครบชุด",
    description: "เซนเซอร์นับชิ้นงานที่บรรจุลงกล่อง (X0) เมื่อครบ 5 ชิ้นให้รอ 3 ticks เพื่อปิดผนึกกล่อง แล้วจึงเปิดสัญญาณส่งกล่องออก (Y0)",
    skill: "counters",
    hintKey: "mixed",
    build: () => shapes.shapeCounterThenTimer("X0", "Y0", 5, 3),
  },
  {
    levelNumber: 96,
    title: "นับชิ้นงานสำเร็จรูปทั้งกะ",
    description: "เซนเซอร์นับชิ้นงานสำเร็จรูป (X0) เมื่อครบ 15 ชิ้นให้สัญญาณ 'ครบเป้าหมายการผลิตกะนี้' (Y0) ทำงาน",
    skill: "counters",
    hintKey: "counter_up",
    build: () => shapes.shapeCtuCount("X0", "Y0", 15),
  },
  {
    levelNumber: 97,
    title: "นับถอยหลังรอบซ่อมบำรุง",
    description: "รอบการทำงานก่อนซ่อมบำรุงเริ่มต้นที่ 6 รอบ ทุกครั้งที่ทำงานเสร็จ 1 รอบ (X0) ตัวนับจะลดลง 1 เมื่อถึง 0 ให้สัญญาณ 'ถึงกำหนดซ่อมบำรุง' (Y0) ทำงาน",
    skill: "counters",
    hintKey: "counter_down",
    build: () => shapes.shapeCtdCount("X0", "Y0", 6),
  },
  {
    levelNumber: 98,
    title: "นับรอบเครื่องจักรก่อนบำรุงรักษา",
    description: "เซนเซอร์นับรอบการทำงานของเครื่องจักร (X0) เมื่อครบ 20 รอบให้สัญญาณแจ้งเตือนบำรุงรักษา (Y0) ทำงาน และกดปุ่มรีเซ็ต (X1) หลังบำรุงรักษาเสร็จ",
    skill: "counters",
    hintKey: "counter_up",
    build: () => shapes.shapeCtuWithReset("X0", "X1", "Y0", 20),
  },
  {
    levelNumber: 99,
    title: "นับผลิตภัณฑ์เฉพาะไลน์ที่เปิดใช้งาน",
    description: "เซนเซอร์นับผลิตภัณฑ์ (X0) จะถูกนับก็ต่อเมื่อไลน์ผลิตนั้นเปิดใช้งานอยู่ (X1) เท่านั้น เมื่อครบ 8 ชิ้นให้ Y0 ทำงาน",
    skill: "counters",
    hintKey: "counter_up",
    build: () => shapes.shapeCtuGated("X0", "X1", "Y0", 8),
  },
  {
    levelNumber: 100,
    title: "ระบบคลังสินค้าอัตโนมัติครบวงจร",
    description:
      "เซนเซอร์นับสินค้าที่จัดเก็บเข้าคลังอัตโนมัติ (X0) เมื่อครบ 8 ชิ้นให้รอ 2 ticks เพื่อให้ระบบยืนยันตำแหน่งจัดเก็บ แล้วจึงเปิดสัญญาณ 'พร้อมรับคำสั่งใหม่' (Y0)",
    skill: "counters",
    hintKey: "mixed",
    build: () => shapes.shapeCounterThenTimer("X0", "Y0", 8, 2),
  },
];

export const ALL_DESCRIPTORS: LevelDescriptor[] = [...basicLogic, ...latching, ...timers, ...counters];
